CXX=g++
CFLAGS=-Wall -std=c++11

CXX (CFLAGS) 

Rectangle.o: Rectangle.cpp
  g++ (CFLAGS) Rectangle.h Rectangle.cpp -c -o Rectangle.o
  
rectangle_calc: main.cpp
  g++ (CFLAGS) Rectangle.o main.cpp -o rectangle_calc
